name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sbsrf/librime
      credentials:
        username: tansongchen
        password: ${{ secrets.pat }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        id: build
        run: |
          rime_deployer --build . /usr/share/rime-data
          rm hypy* bihua* zhlf* *.extended.dict.yaml *2.schema.yaml user.yaml
          zip -r sbsrf.zip build lua squirrel trime weasel *.yaml *.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: sbsrf.zip
