name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sbsrf/librime
      credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.sbsrf }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        id: build
        run: |
          mv sbxlm/* .
          rime_deployer --build . /usr/share/rime-data
          rm bihua* zhlf* sbfc* *.extended.dict.yaml *2.schema.yaml user.yaml sbpy.base.dict.yaml sbpy.ext.dict.yaml sbpy.tencent.dict.yaml
          zip -r sbsrf.zip build lua opencc *.yaml *.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: sbsrf.zip
